"""Add is_anomaly

Revision ID: 1bb29ef41904
Revises: 27aa1270568c
Create Date: 2026-06-06 14:39:09.569799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb29ef41904'
down_revision: Union[str, None] = '27aa1270568c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('is_anomaly', sa.Boolean(), nullable=True))
    op.alter_column('quotations', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('quotations', 'delivery_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'delivery_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotations', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('quotations', 'is_anomaly')
    # ### end Alembic commands ###
