from pydantic import BaseModel, EmailStr, Field
from app.models.models import UserRole
from datetime import datetime


class UserBase(BaseModel):
    """
    Base Pydantic schema for shared user attributes.
    """
    email: EmailStr = Field(..., description="Unique email address of the user")
    full_name: str | None = Field(None, description="Full name of the user")
    role: UserRole = Field(
        UserRole.PROCUREMENT_OFFICER,
        description="User role determining system permissions (admin, procurement_officer, manager, vendor)"
    )
    is_active: bool = Field(True, description="Flag indicating if the user account is active")


class UserCreate(UserBase):
    """
    Schema for incoming user registration request.
    Includes password validation.
    """
    password: str = Field(..., min_length=6, description="Password for the user account (min 6 characters)")


class UserUpdate(BaseModel):
    """
    Schema for updating user details.
    Allows partial updates as all fields are optional.
    """
    email: EmailStr | None = Field(None, description="Updated email address")
    full_name: str | None = Field(None, description="Updated full name")
    password: str | None = Field(None, min_length=6, description="Updated password (min 6 characters)")
    role: UserRole | None = Field(None, description="Updated user role")
    is_active: bool | None = Field(None, description="Updated active flag")


class UserResponse(UserBase):
    """
    Response schema returning user information.
    Excludes sensitive fields like password.
    """
    id: int = Field(..., description="Unique user ID auto-generated by database")
    created_at: datetime = Field(..., description="Timestamp of when the user account was created")

    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "id": 1,
                "email": "procurement@company.com",
                "full_name": "John Doe",
                "role": "procurement_officer",
                "is_active": True,
                "created_at": "2026-06-06T12:00:00Z"
            }
        }
    }
